[versions]
kotlin-version = "1.9.0"
koin-version = "3.5.3"
retrofit-version = "2.9.0"
interceptor-version = "4.11.0"
junit-version = "5.9.2"
mokito-kotlin-version = "4.1.0"
mokito-junit-version = "5.3.0"
arch-core-testing-version = "2.2.0"
coroutines-test-version = "1.7.0"
coroutines-version = "1.7.0"
room-version = "2.5.0"
turbine-version = "1.0.0"
coil-version = "2.1.0"

[libraries]
kotlin-android-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "kotlin-version" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-version" }
koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin-version" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin-version" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-version" }

squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
squareup-retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit-version" }
okhttp-loggin-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "interceptor-version" }

junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-version" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-version" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-version" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mokito-kotlin-version" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mokito-junit-version" }
arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch-core-testing-version" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test-version" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine-version" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-version" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-version" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-version" }

[bundles]
retrofit-deps = ["squareup-retrofit", "squareup-retrofit-converter", "okhttp-loggin-interceptor"]
unit-tests-deps = ["junit-api", "junit-params", "junit-engine", "mockito-kotlin", "mockito-junit", "arch-core-testing", "coroutines-test", "koin-test", "turbine"]
coin-deps = ["koin", "koin-android", "koin-compose"]
coroutines-deps = ["coroutines-core", "coroutines-android"]